[WIP] Refetch control
EQWorks/react-labs pull request #123
Opened 2020-09-21 18:06 UTC by SamSverko

I’m in the process of building out this “agnostic data fetcher UI” (think of the Gmail refresh button). Where it:

- :white_check_mark: Fetches your data using [react-query](https://react-query.tanstack.com/).
- :white_check_mark: Displays visual feedback (`loading` & `error` states).
- :x: Passes the data back to its parent component?

I’m not sure how to handle the last part. Any thoughts/help?

2020-09-21 19:41 UTC, woozyking requested changes

2020-09-21 19:41 UTC, woozyking commented on src/theme/index.js
> +}
these two do different things. both should be kept.

```js
// this is the same as export { DefaultTheme }
// which is a named-export
export const DefaultTheme = ...
                                                     
// this is for backward compatibility
// so it doesn't break previous use as module default
export default DefaultTheme
```

2020-09-21 19:41 UTC, woozyking commented on stories/refetch-data.stories.js
> +  <RefetchData {...args} />
perhaps provide a better demonstration with an actual `update` function for `onClick` which mutates a `status` state.

`setTimeout` can be used to emulate something that's happening that takes some time (such as performing an API call) so `loading` can be prominent for the emulation period. and `error` status can potentially be pseudo-randomly set by using `Math.random` to further emulate a realistic API call experience.

2020-09-21 19:41 UTC, woozyking commented on src/refetch-data.js
> +      </div>
one of the important factors for the use of libraries such as `react-query` is the capability to emulate "real-time" updates, so it's quite useful (but not necessarily required) to provide a visual indicator for _when_ the data was last updated, such as accepting an `updated` prop which is in the form a JS Date object, which then can be formatted using `localeString` (or provided as a string to be displayed as-is)

2020-09-21 19:52 UTC, SamSverko commented on src/theme/index.js
> +}
Ohh, I see how that backward compatibility option is useful, thank you.

2020-09-22 16:40 UTC, tlowande commented on stories/refetch-data.stories.js
> +  }
I lost track of this variable. Where is `status` declared again or is it used for something??

2020-09-22 16:41 UTC, tlowande commented on src/theme/index.js
> +export const DefaultTheme = createMuiTheme({
the final export, on line 33, shouldn't it be for ThemeProvider?

2020-09-22 16:57 UTC, tlowande commented on src/refetch-data.js
> +  lastUpdated: PropTypes.instanceOf(Date),
I noticed that there's no tooltip on the first render. I guess this prop could be `required` so the button is always initialized with the last time it was updated (prob as soon as data was fetched for the first time). Or set a default value to just `now` if that makes sense. 

There's also no tooltip if `error` but I guess if you have the porp as `required` or `default` should be fine.

2020-09-22 17:48 UTC, SamSverko commented on src/theme/index.js
> +export const DefaultTheme = createMuiTheme({
Not in our case because we've previously imported the `theme` object directly from `/src/theme/index`. It's just to provide some backward compatibility.

Any future cases will use this: `import { ThemeProvider, Theme } from '@eqworks/react-labs'`.

2020-09-22 17:50 UTC, SamSverko commented on stories/refetch-data.stories.js
> +  }
Status is a prop for the [RefetchData](https://github.com/EQWorks/react-labs/blob/aecb4c8a2019c7d38aa2377047f6a79171df6fae/src/refetch-data.js) component.

2020-09-22 17:51 UTC, SamSverko commented on stories/refetch-data.stories.js
> +  }
The stories I wrote for the `RefetchData` component are purely for demonstration purposes. They simple "mock" retrieving data to showcase the `status` displays of `loading` and `error`.

2020-09-22 17:52 UTC, SamSverko commented on src/refetch-data.js
> +  lastUpdated: PropTypes.instanceOf(Date),
There's no tooltip on first render because you need to activate the refetch button to then be able to see when it was last called. If it was never called (i.e. on first render without selecting it), the tooltip should not become visible on hover.

2020-09-22 18:23 UTC, woozyking requested changes

2020-09-22 18:23 UTC, woozyking commented on src/refetch-data.js
> +        setLastUpdatedDisplay('Updated more than an hour ago')
it's actually better to just show when _exactly_ they were updated as the UI will not rerender these values if `lastUpdated` doesn't change, say, for an hour, yet the display would still show something like "Updated just now", which may be misleading.

so you can actually use something like [here](https://github.com/EQWorks/snoke/pull/829/files#diff-b3be9e89df5c01b0c87735a8886b6b97R19):

```js
const formatUpdated = (updated) => (updated.toDateString() === new Date().toDateString()
  ? updated.toLocaleTimeString()
  : updated.toLocaleString())
```

which keeps a decent balance for any time from "today" to be shortened by having the date portion omitted.

2020-09-22 18:23 UTC, woozyking commented on src/refetch-data.js
> +        setLastUpdatedDisplay('Updated more than an hour ago')
another option, for if we want to keep the "ago" logic, is to attach an active effect through "new Date()" to force the re-render and let the "ago" display to be refreshed

2020-09-22 18:23 UTC, woozyking commented on stories/refetch-data.stories.js
> +      setLastUpdated(new Date(Date.now()))
`new Date()` is actually equivalent to `new Date(Date.now())` by value

```js
new Date().toISOString() === new Date(Date.now()).toISOString() // -> true
```

2020-09-22 18:23 UTC, woozyking commented on stories/refetch-data.stories.js
> +  }
variable/reference `status` doesn't exist in this module (`refetch-data.stories.js`), nor this `Default` component

![status](https://user-images.githubusercontent.com/2837532/93921650-d550c100-fcde-11ea-9de7-1dc31ee0c355.png)

perhaps you meant to just use `fetchStatus` here, and `setFetchStatus('error')` in the HTTP get request?

```js
try {
  const { data } = axios.get(...)
} catch(error) {
  setFetchStatus('error')
}
```

2020-09-22 18:23 UTC, woozyking commented on stories/refetch-data.stories.js
> +    window.setTimeout(() => {
if an actual remote HTTP API is involved, then `setTimeout` is probably not needed to emulate that.

also, why not make use of this data by displaying it in the story?

2020-09-22 18:23 UTC, woozyking commented on stories/refetch-data.stories.js
> +      return data
what does this `return` do?

2020-09-22 18:28 UTC, woozyking commented on src/refetch-data.js
> +            onMouseUp={handleClick}
should we disable the button when `status === 'loading'`? otherwise it'll perform as many times of `handleClick` as the button is clicked, which can lead to unexpected abuse.

2020-09-23 13:26 UTC, SamSverko commented on stories/refetch-data.stories.js
> +  }
I'm confused here. Doesn't it not matter how the fetch is implemented in the stories because they were mocked just to visualize the `RefetchData` UI updates?

`status` is just a prop of the `RefetchData` component. You can see it here inside `refetch-data.stories.js`:
```jsx
return <RefetchData
    status={fetchStatus}
    fetchDataFunction={fetchData}
    lastUpdated={lastUpdated}
  />
```

2020-09-23 13:27 UTC, SamSverko commented on src/refetch-data.js
> +        setLastUpdatedDisplay('Updated more than an hour ago')
I did add an interval that occurs every minute to update the lastUpdated display value:
```jsx
const updateLastUpdatedTimer = setInterval(() => {
  displayLastUpdated()
}, 60 * 1000)
```

This works well. If you select the button and wait 1 minute, the lastUpdated display will update to "Updated 1 minute ago" etc...

2020-09-23 13:29 UTC, SamSverko commented on stories/refetch-data.stories.js
> +      setLastUpdated(new Date(Date.now()))
If I use `new Date().toISOString()` instead of `new Date(Date.now()).toISOString()`, I get this error from the `RefetchData` component: 
```
startTime.getTime is not a function
```

2020-10-13 14:45 UTC, tlowande commented on stories/refetch-data.stories.js
> +  }
ye, it does not matter how you're fetching your data, but you're not handling the error here. 

so, inside this story function you built, `status` doesn't exist. `status` is what you're passing to the `<RefetchData>` component, in this case, you named it `fetchStatus`. The story (the outer function that mounts `<RefetchData>`) only knows `fetchStatus` as a variable.

so just to simulate the error condition, you'd need a `try/catch` block, to `setFetchStatus('error')` so your component will handle it as it should.

or just remove this `if` block since you made a story specifically for `error`. Although imo as a user would like to see the implementation here. So:

```
  const fetchData = async () => {
    setFetchStatus('loading')
     try {
       const { data } = await axios.get('https://jsonplaceholder.typicode.com/users/1')
       window.setTimeout(() => {
         setFetchStatus('none')
         setLastUpdated(new Date(Date.now()))
         setFetchedData(data)
       }, 1000)
      } catch(error){
       setFetchStatus('error')
      }
  }
```

2020-10-13 14:57 UTC, tlowande commented on stories/refetch-data.stories.js
> +      setLastUpdated(new Date(Date.now()))
I tried to replicate but I couldn't sam, when I do `new Date()` for the story, I don't see the component error. Same for the component itself, where I also cahanged to `new Date()` and didn't experience errors:
```  
const displayLastUpdated = () => {
    if (lastUpdated) {
      const startTime = lastUpdated
      const currentTime = new Date()
      ...
}
```

2020-10-13 14:59 UTC, tlowande commented on src/refetch-data.js
> +  }
how do I trigger this? I tried pressing `return` and `space` but doesn't trigger. Was it made thinking of mobile support?

2020-10-13 15:08 UTC, tlowande commented on src/refetch-data.js
> +        setLastUpdatedDisplay('Updated more than an hour ago')
seems to be working, just say my `14min ago` here.

2020-10-13 15:15 UTC, SamSverko commented on stories/refetch-data.stories.js
> +  }
Ohh, that was super helpful @tlowande thank you for the clarification :)

2020-10-13 15:26 UTC, SamSverko commented on stories/refetch-data.stories.js
> +      setLastUpdated(new Date(Date.now()))
Using `const currentTime = new Date().toISOString()` for line 111 gives me the error. Thoughts @woozyking ?

2020-10-13 15:28 UTC, SamSverko commented on src/refetch-data.js
> +      const currentTime = new Date(Date.now())
This is missing the `.toISOString()` method. When that's added, it breaks with a very unhelpful error message.

2020-10-13 15:28 UTC, SamSverko commented on src/refetch-data.js
> +  }
This is for keyboard support, when you tab and focus onto the element.

2020-10-13 19:27 UTC, tlowande approved these changes

2020-10-13 19:38 UTC, woozyking approved these changes

2020-10-13 20:08 UTC, merged