[G2M] Inputs
EQWorks/react-labs pull request #133
Opened 2020-10-09 19:11 UTC by SamSverko

Created, styled, and wrote rendering tests for the following inputs to better match our design:
- `Checkbox`
- `Radio`
- `Switch` (what a pain to style this one 😅)

Moved the follow inputs to "deprecated" status:
- `StyledCheckbox`
- `StyledRadio`
- `StyledSwitch`

Exported `FormControl`, `FormControlLabel`, `FormGroup`, `FormLabel`, and `RadioGroup` from `material-ui` as `react-labs` components, so we could `import { FormControl } from '@eqworks/react-labs'`.

2020-10-09 20:10 UTC, woozyking requested changes

2020-10-09 20:10 UTC, woozyking commented on src/checkbox.js
> +  '1.003 0 00-1.42 1.42l3 3c.18.18.43.29.71.29s.53-.11.71-.29l5-5A1.003 1.003 0 0012 5z\' fill=\'%23fff\'/%3E%3C/svg%3E")'
this would be hard to read and/or extract out for reusing.

better option:

```js
const checkSVG = `
  <svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16'>
    <path 
      fill-rule='evenodd'
      clip-rule='evenodd'
      d='M12 5c-.28 0-.53.11-.71.29L7 9.59l-2.29-2.3a1.003 1.003 0 00-1.42 1.42l3 3c.18.18.43.29.71.29s.53-.11.71-.29l5-5A1.003 1.003 0 0012 5z'
      fill='#fff'
    />
  </svg>
`
const CHECKMARK = `url("data:image/svg+xml;charset=utf-8,${encodeURIComponent(checkSVG)}")`
```

2020-10-09 20:10 UTC, woozyking commented on src/checkbox.js
> +  disabled: PropTypes.bool,
this is not needed and can just relay through what MUI Checkbox is expecting

2020-10-09 20:10 UTC, woozyking commented on src/checkbox.js
> +  onChange: PropTypes.func,
this is not used as it's managed by its internal handler `checkOnChange`

2020-10-09 20:10 UTC, woozyking commented on src/switch.js
> +}
for implementation, this is not needed as all props are relayed into MUI Switch

for "intellisense" code suggestion purposes. this can be done through

```js
StyledSwitch.propTypes = Switch.propTypes
StyledSwitch.defaultProps = Switch.defaultProps
```

2020-10-13 15:33 UTC, woozyking approved these changes

2020-10-13 15:38 UTC, DoParkEQ commented on src/checkbox.js
> +        outline: `1px solid ${theme.palette.primary.main}`,
Nice work! a quick question — Is there a specific reason for drawing a box when it is focused?

2020-10-13 15:38 UTC, DoParkEQ approved these changes

2020-10-13 15:49 UTC, SamSverko commented on src/checkbox.js
> +        outline: `1px solid ${theme.palette.primary.main}`,
There needs to be a visible outline for accessibility, [WCAG 2.1 section 2.4.7](https://www.w3.org/WAI/WCAG21/quickref/#focus-visible).

2020-10-13 18:11 UTC, merged